### ISSUE TITLE
swinging animation card with images

### ISSUE THREAD

**Issue by arzitmahajan** [Junior-Developer-Group/hacktoberfest-2022#1]

**Comment by mateahoward** [comment]
Hi @arzitmahajan, as you're aware HacktoberFest isn't happening just yet - therefore we're not accepting issues or PRs at this time. You raised an issue about the placeholder cards which will be used by participants when the time comes and styled accordingly to their wishes, 

As there are no 'swinging animation card' requirements mentioned inside our ReadMe file and you haven't added a description to your raised issue I'll have to take this request as spam and mark it as such. 

Please get familiar with the rules of HacktoberFest and create your contributions accordingly.
