### ISSUE TITLE
Transition & Hovering Effects In Card

### ISSUE THREAD

**Issue by Namanb454** [Junior-Developer-Group/hacktoberfest-2022#2]
- There is a simple card without any hovering, transforms & transitions.

Proposal:
- I will add hovering effects, transition effects, rotating effect with the use of only CSS.
- Responsiveness of the site will be considered properly without affecting any other components of the site.
- The cards will absolutely work and look fantabulous.

**Comment by Namanb454** [comment]
@Junior Please assign this issue to me.

**Comment by Johnnyteck** [comment]
I guess the effect on each card can be designed by each participant. Also the effects are meant to be different and unique for each submission. Your good thoughts are highly appreciated.

**Comment by mateahoward** [comment]
Hi @Namanb454,  as you're aware HacktoberFest isn't happening just yet - therefore we're not accepting issues or PRs at this time. You raised an issue about the placeholder cards which will be used and styled by participants when the time comes, as our ReadMe file says.

There hasn't been a requirement for the mentioned change, and in fact, most of your proposed changes already exist and do not need your input. 

As this change proposal doesn't bring any value to this project and is done ahead of time (before HacktoberFest has started), I'll have to take this request as spam and mark it as such.

Please get familiar with the rules of HacktoberFest and create your contributions accordingly.
