### ISSUE TITLE
Fix: Fish bubbles are missing on mobile screen size @375px viewport width

### ISSUE THREAD

**Issue by J3ffJessie** [Junior-Developer-Group/hacktoberfest-2022#20]
Task Description: 

- [x] Inspect website and toggle device toolbar to have responsive viewport.
- [x] Set viewport width to 375px
- [x] Look at Jonnie's fish and notice the bubbles are not displayed

Check the styling for bubbles at the smaller screen size to ensure that bubbles are displayed at the smallest screen sizes. May have to utilize media queries to ensure styles across different screen sizes.

**Comment by Jonniie** [comment]
Did that deliberately for smaller screens
