### ISSUE TITLE
Some changes in design layout.

### ISSUE THREAD

**Issue by dvig14** [Junior-Developer-Group/hacktoberfest-2022#3]
can u assign me this.

**Comment by Jonniie** [comment]
Hi @dvig14 , as you're aware HacktoberFest isn't happening just yet - therefore we're not accepting issues or PRs at this time. You raised an issue about some changes in the design layout without explaining what the changes are. 

Though, there hasn't been a requirement for any change in layout whatsoever and so this suggested change proposal doesn't bring any value to this project and is done ahead of time (before HacktoberFest has started), I'll have to take this request as spam, and mark it as such.

Please get familiar with the rules of HacktoberFest and create your contributions accordingly.
